-- Create productcluster table

CREATE TABLE productcluseter as
SELECT
ITEM_SK,
sum(SELLING_RETAIL_AMT) as TOTAL_REVENUE,
count(distinct TRANSACTION_RK) as BASKETS,
count(distinct CUSTOMER_SK) as DISTINCT_CUSTOMERS,
avg(SELLING_RETAIL_AMT/NULLIF(ITEM_QTY,0)) as AVERAGE_PRICE
FROM dataset01.sales219
GROUP BY ITEM_SK
ORDER BY TOTAL_REVENUE DESC
LIMIT 2000;

-- Extract productcluser table as productcluster.csv (Keep the row with column names)

CREATE TABLE customer_cluster AS
SELECT
    CUSTOMER_SK,
    COUNT(ITEM_SK) AS NUM_PRODUCTS_BOUGHT,
    COUNT(DISTINCT ITEM_SK) AS NUM_DISTINCT_PRODUCTS_BOUGHT,
    SUM(SELLING_RETAIL_AMT) AS TOTAL_REVENUE,
    ,
    SUM(SELLING_RETAIL_AMT) / COUNT(DISTINCT TRANSACTION_RK) AS AVG_SALES_PER_VISIT
FROM
    dataset.sales
GROUP BY
    CUSTOMER_SK
ORDER BY TOTAL_REVENUE DESC
LIMIT 2000;